name: octopus api dev deploy


on:
push:
branches:
- dev


env:
SERVER_HOST: ${{ secrets.DEPLOY_HOST_PROD }}
SERVER_USER: ${{ secrets.DEPLOY_USER_PROD }}
SERVER_PATH: /var/www/qa.fiery-octopus.by/html


jobs:


deploy:
runs-on: ubuntu-latest


steps:
- uses: actions/checkout@v3


# Install ssh key
- name: Install SSH Key
  uses: shimataro/ssh-key-action@v2.3.1
  with:
    key: "${{ secrets.SSH_PRIVATE_KEY }}"
    known_hosts: "just-a-placeholder-so-we-dont-get-errors"


- name: Generate auth hosts
  run: ssh-keyscan -H ${{ env.SERVER_HOST }} >> ~/.ssh/known_hosts


# Deploy
- run: rsync --archive --compress --progress . ${{ env.SERVER_USER }}@${{ env.SERVER_HOST }}:${{ env.SERVER_PATH }}


