name: octopus dev deploy

on:
 push:
   branches:
     - dev

jobs:
 deploy:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     # Setup key
     - run: set -eu
     - run: mkdir "$HOME/.ssh"
     - run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > "$HOME/.ssh/key"
     - run: chmod 600 "$HOME/.ssh/key"
     - name: Setup PHP
       uses: shivammathur/setup-php@v2
       with:
         php-version: 8.3
     # Deploy
     - name: Copy .env
       run: php -r "file_exists('.env') || copy('.env.example', '.env');"
     - name: Install dependencies
       run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --ignore-platform-reqs
     - name: Set required directory permissions
       run: | 
        chmod -R 777 storage bootstrap/cache
        sudo chmod -R 777 vendor
     - name: Set .env
       shell: bash
       run: echo "${{ vars.QA_ENV }}" > .env
     - name: Update app key
       shell: bash
       run: php artisan key:generate
     - name: Install Dependencies
       run: npm install
     - name: Clean install dependencies and build
       run: |
        npm run prod
     - run: rsync -e "ssh -Tv -p ${{secrets.SERVER_PORT}} -i $HOME/.ssh/key -o StrictHostKeyChecking=no -l ${{secrets.DEPLOY_USER_PROD}}" --archive --compress --delete . ${{secrets.DEPLOY_USER_PROD}}@${{secrets.DEPLOY_HOST_PROD}}:/var/www/qa.fiery-octopus.by/html
     - name: Run migrations on server
       uses: appleboy/ssh-action@v0.1.10
       with:
        host: ${{ secrets.DEPLOY_HOST_PROD }}
        username: ${{ secrets.DEPLOY_USER_PROD }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        command_timeout: 3m
        script: | 
         cd ../var/www/qa.fiery-octopus.by/html
         php artisan migrate
         php artisan db:seed
         
